server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-plannacer.c5ui2oswmdqq.us-east-2.rds.amazonaws.com:3306/planSumarSalud
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
      ddl-auto: update
    generate-ddl: true
    show-sql: true
jwt:
  expirationMs: 3600000

